languageCode = 'en-us'
title = '–°–∞–π—Ç –ë–æ—Ä–∏—Å–æ–≤–∞ –Ü–ª–ª—ñ'
theme = "hugo-theme-hello-friend"

[taxonomies]
  tag="tags"

baseurl = "https://borisovvilyaa.github.io/SimpleBlog"
languageCode = "en-us"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.

paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # OS theme is default when not provided, but you can force it to "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

[languages]
  [languages.en]
    title = "Borusov"
    subtitle = "Blog review"
    keywords = ""
    copyright = ""
    menuMore = "–©–µ –º–µ–Ω—é"
    writtenBy = "–ê–≤—Ç–æ—Ä: "
    readMore = "–ß–∏—Ç–∞—Ç–∏ –¥–∞–ª—ñ"
    readOtherPosts = "–Ü–Ω—à—ñ –ø–æ—Å—Ç–∏–∫–∏"
    newerPosts = "–ù–æ–≤—ñ—à—ñ –ø–æ—Å—Ç–∏"
    olderPosts = "–°–¢–∞—Ä—ñ –ø–æ—Å—Ç–∏"
    minuteReadingTime = "–•–≤–∏–ª–∏–Ω–∞ —á–∏—Ç–∞–Ω–Ω—è"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "Borusov"
      logoHomeLink = ""
    # or
    #
    # path = "/img/logo.svg"
    # alt = "–õ–æ–≥–æ"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "–Ü–¥–µ—è —Å–∞–π—Ç—É üëÄ"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "–¢–µ–≥–∏"
        url = "/tags"
      [[languages.en.menu.main]]
        identifier = "post"
        name = "–°—Ç–∞—Ç—Ç—ñ"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "telegram"
        name = "tg"
        url = "https://t.me/illiaborusov"